name: desktop_notifications
version: 0.3.0

description:
  Allows notifications to be sent on Linux desktops using the desktop notifications specification.

homepage: https://github.com/canonical/desktop_notifications.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.4.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
