name: desktop_notifications
version: 0.0.0-dev.1

description:
  Allows notifications to be sent on Linux desktops using the desktop notifications specification.

homepage: https://github.com/canonical/desktop_notifications.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  dbus: ^0.0.0-dev.13

dev_dependencies:
  pedantic: ^1.9.0
